### ISSUE TITLE
incorrect result for where clause?

### ISSUE THREAD

**Issue by fountainer** [fritzgrabo/ob-dsq#1]
Here is the org table I use:
```org
#+name: score
|  ID | score |
|-----+-------|
| 123 |    90 |
| 125 |    99 |
| 126 |   100 |
```
This code in org source block
```
select *
  from {}
 where score > 95
```
gives the following result:
```org
|  ID | score |
|-----+-------|
| 125 |    99 |
```
In contrast, the following code
```
select *
  from {}
 where score < 95
```
yields
```
|  ID | score |
|-----+-------|
| 123 |    90 |
| 126 |   100 |
```
It seems that the numbers are treated as strings.

**Comment by fountainer** [comment]
It seems that `dql` cannot "guess" the type of data. An explicit cast is required. The following code gives the right answer.
```
select *
  from {}
 where cast(score as int) < 95
```

**Comment by fritzgrabo** [comment]
Thanks for the detailed report and the example data: I'm able to replicate the unexpected behavior locally.

In fact, I'm able to replicate it with just `dsq` and a CSV file on a shell, outside of Emacs:

```shell
$ cat score.csv
ID,score
123,90
125,99
126,100

$ dsq score.csv "select * from {} where score > 95"
[{"ID":"125","score":"99"}]
```

Note that the issue goes away when using JSON as an input file:

```shell
$ cat score.json
[{"id":123, "score":90},
{"id":125, "score":99},
{"id":126, "score":100}]

$ dsq score.json "select * from {} where score > 95"
[{"id":125,"score":99},
{"id":126,"score":100}]
```

Also note how the `"99"` in the output of the CSV example is quoted, while the `99` in the output of the JSON example is not.

My assumption is that `dsq` treats all values from a CSV as strings, which would explain the behavior you observed as  `ob-dsq` exports the Org data that it queries as temporary CSV files. That assumption is in line with what you found out, too, so that's a good sign 😅 .

I found and fixed [a similar issue](https://github.com/multiprocessio/datastation/pull/205) in Datastation (which `dsq` uses) a while ago -- maybe this is related.

I'll have a look at the related code in Datastation when time permits and update here if I find something that I can fix easily. If can't, we should raise this on Detestation's side and ask for help there.

**Comment by fritzgrabo** [comment]
@fountainer, I opened an issue in the DataStation repository with a proposal for a fix (see the link above). Hopefully, the unexpected behavior you noticed will go away in an upcoming version of `dsq`. Thanks again for raising this! 🙌

**Comment by fountainer** [comment]
Thanks for fixing this bug and creating this package. This package would be very useful when the bug in `Datastation` is fixed.

**Comment by fritzgrabo** [comment]
@fountainer, this was fixed in `dsq` now. If you upgrade both `dsq` and `ob-dsq` to their latest versions, you should get the expected results without any type-casting in the SQL query.

Thanks again for raising the issue, both `dsq` and `ob-dsq` are better than before now because of it 🙌

**Comment by fountainer** [comment]
Thanks. It works as expected.
