### ISSUE TITLE
ob-dsq returns columns in seemingly random order

### ISSUE THREAD

**Issue by vonHabsi** [fritzgrabo/ob-dsq#3]
I've just started using `ob-dsq` and have noticed that with one table columns are rearranged.

Is that a known flaw of `ob-dsq` or is it caused by the `dsq` program itself

**Comment by fritzgrabo** [comment]
Heya @vonHabsi, and thanks for reaching out; I'm glad you're giving `ob-dsq` a try!

Unfortunately, as you suspected, the table columns in the output of `dsq` are indeed unordered -- see https://github.com/multiprocessio/dsq#output-column-order for details. I don't think that `dsq` will change that since it's no longer actively maintained.

However, `ob-dsq` offers `org-babel-dsq-post-execute-hook` which you could use to update the query results before they're displayed. The hook is run in the context of the buffer that holds the JSON query result from `dsq`, so you could easily pipe that through `jq`, or use plain elisp to work some magic.

Let me know if that helps!

Best, Fritz
